### ISSUE TITLE
create appifyr app

### ISSUE THREAD

**Issue by arihanth-jain** [retowyss/appify#7]
I was wondering if it no more possible to create an app (appifyr::create_app()). How would one obtain the required boiler plate template ?

with appifyr::build_app() i get the below error
_Error in render_site(input = app_dir) : No site generator found._

Thanks

**Comment by retowyss** [comment]
You can get a working template by cloning retowyss/sepals-and-petals. Please let me know at what point the getting started docs are unclear so I can update them.
